main: org.rollthedice.rtd
name: RollTheDice
version: 0.3
author: Inspector Soviet
description: Roll The Dice plugin
commands:
  rtd:
    description: Roll the dice!
    usage: /rtd
  rtdinfo:
    description: View plugin version
    usage: /rtdinfo
permissions:
  rtd.notify:
    description: Get notified about new updates
    default: op
  rtd.use:
    description: Allows to use RTD
    default: op     